### ISSUE TITLE
/help doesn't work

### ISSUE THREAD

**Issue by NikitaRus** [weaponrex/lugormod#1]
I've just tested this version of lugormod and can't figure out how to make /help work.

It doesn't work logged in and either logged off (I through it was admin related issue but no..)

Should download the branch and check by myself...

**Comment by andresxvar** [comment]
Yes it's not documented, but the command /help was changed to /helpme.
Because OpenJK now uses /help in client side (or game side?) and it overrides the server.

The modified code is in g_cmds.cpp around line ~4300

```
if (Q_stricmp (cmd, "helpme") == 0) {
		Cmd_Help_f(ent);
		retur
```

**Comment by andresxvar** [comment]
fixed by checking 4 characters only:
```
if (Q_strncmp (cmd, "help",4) == 0) {
		Cmd_Help_f(ent);
		return;
	}
```
players can use "help", "helpm", "help123"...
